#!/usr/bin/env python3
"""
PharmRes manuscript -- the model, and Figures 3 and 4.

Parameter dictionary (single source of truth for every computed value):
    K_S = 29  uM   SIRT1 Michaelis constant for NAD+ (acetyl-H3K9)
    K_i = 175 uM   SIRT1 inhibition constant for nicotinamide (IC50 = Ki)
    N0  = 100 uM   nuclear free NAD+, unstressed
    N_d = 25  uM   nuclear free NAD+, assumed fourfold depletion
    M0  = 30  uM   resting intracellular nicotinamide

Output: figures are drawn at 190 mm (Elsevier full-page width) with 8 pt text,
above the 7 pt minimum at final printed size. Line artwork is written as EPS
(vector) with a 600 dpi TIFF alongside.

Figure 1 of the manuscript is generated by PharmRes_Figure1.py.
Figure 2 is a hand-drawn pathway schematic and has no generating script.
"""
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# ----------------------------------------------------------------- parameters
K_S, K_I = 29.0, 175.0
N_UN, N_DP, M0 = 100.0, 25.0, 30.0
ETA = 0.34                      # highest published elasticity

FONT = "Nimbus Sans"            # Helvetica-metric; substitute if unavailable
FS   = 8.0                      # >= 7 pt at final printed size
W = 190/25.4                    # print width, inches (190 mm)
AC, BC, GY, LG = "#1f6fb4", "#b81f2e", "#555555", "#8c8c8c"
SHADE, GREY = "#dce9f5", "#ececec"

plt.rcParams.update({
    "font.family": FONT, "font.size": FS,
    "axes.labelsize": 11, "axes.titlesize": 11,
    "xtick.labelsize": 11, "ytick.labelsize": 11,
    "legend.fontsize": FS, "axes.linewidth": 0.9,
    "svg.fonttype": "none", "ps.fonttype": 42, "pdf.fonttype": 42,
})

import os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures") + os.sep
os.makedirs(OUT, exist_ok=True)


def save(fig, stem):
    fig.savefig(OUT + "PharmRes_" + stem + ".eps", format="eps", bbox_inches="tight")
    fig.savefig(OUT + "PharmRes_" + stem + ".tif", format="tiff", dpi=600,
                bbox_inches="tight", pil_kwargs={"compression": "tiff_lzw"})
    fig.savefig(OUT + "PharmRes_" + stem + ".png", dpi=150, bbox_inches="tight")
    plt.close(fig)


def sat(N):                     # fractional saturation of SIRT1
    return N / (K_S + N)


def gain(N, N0):                # G(N) relative to the resting state
    return sat(N) / sat(N0)


def penalty(M):                 # P(M), exit penalty
    return (1.0 + M0 / K_I) / (1.0 + M / K_I)


def eta_req(M, N0):
    return M * (K_S + N0) / (K_S * (K_I + M))


G_UN, G_DP = (K_S + N_UN) / N_UN, (K_S + N_DP) / N_DP          # 1.29, 2.16
M_UN = K_I * (G_UN * (1 + M0 / K_I) - 1)                       # 89
M_DP = K_I * (G_DP * (1 + M0 / K_I) - 1)                       # 268

# =========================================================== FIGURE 1
ROWS = [
    ("h", "HUMAN SKIN, topical", "", "", None, None),
    ("d", "Myristyl nicotinate 5%", "Forearm", "12 wk, 5%", 1.25, "5, 6"),
    ("d", "Niacinamide 4%", "Forearm", "8 wk, 4%", 1.00, "5"),
    ("h", "MOUSE SKIN, topical", "", "", None, None),
    ("d", "Myristyl nicotinate", "Dorsum", "\u2014", 1.43, "5"),
    ("h", "CULTURED CELLS, 6 h", "", "", None, None),
    ("d", "Nicotinic acid", "HEK293", "5\u201310 \u00b5M", 2.00, "15"),
    ("d", "Nicotinamide", "HEK293", "20 \u00b5M", 1.00, "15"),
    ("d", "Nicotinamide", "HEK293", "5 mM", 1.31, "15"),
    ("d", "Nicotinic acid", "NHEK", "10 \u00b5M", 1.30, "19"),
    ("d", "Nicotinic acid + FK866", "NHEK", "10 \u00b5M", 1.30, "19"),
    ("d", "Nicotinic acid mononucleotide", "NHEK", "30\u2013100 \u00b5M", 1.50, "19"),
    ("d", "Nicotinic acid riboside", "NHEK", "100 \u00b5M", 1.10, "19"),
    ("d", "Nicotinamide", "NHEK", "100 \u00b5M", 0.95, "19"),
    ("d", "Nicotinamide mononucleotide", "NHEK", "100 \u00b5M", 1.00, "19"),
    ("d", "Nicotinamide riboside", "NHEK", "100 \u00b5M", 1.00, "19"),
]
ACID = {"Myristyl nicotinate 5%", "Myristyl nicotinate", "Nicotinic acid",
        "Nicotinic acid + FK866", "Nicotinic acid mononucleotide",
        "Nicotinic acid riboside"}

n = len(ROWS)
fig = plt.figure(figsize=(W, 0.34 * n + 1.15))
gs = fig.add_gridspec(1, 2, width_ratios=[2.55, 1.0], wspace=0.03)
tb, pl = fig.add_subplot(gs[0]), fig.add_subplot(gs[1])

tb.set_xlim(0, 1); tb.set_ylim(-1.9, n); tb.axis("off")
COLX = (0.00, 0.625, 1.0)
HEAD = ("Agent", "Model", "Exposure")
for x, h in zip(COLX, HEAD):
    tb.text(x, n - 0.35, h, fontsize=FS, weight="bold", va="center",
            ha="right" if h == "Exposure" else "left")
tb.plot([0, 1], [n - 0.85] * 2, color="0.25", lw=1.0, clip_on=False)

for i, (kind, agent, system, exp, val, ref) in enumerate(ROWS):
    y = n - 1.5 - i
    if kind == "h":
        tb.text(0.0, y, agent, fontsize=FS-0.5, style="italic",
                weight="bold", color="0.30", va="center")
        tb.plot([0, 1], [y - 0.5] * 2, color="0.80", lw=0.7, clip_on=False)
        continue
    col = AC if agent in ACID else BC
    tb.text(COLX[0], y, agent, fontsize=FS, color=col, va="center")
    tb.text(COLX[1], y, system, fontsize=FS, color="0.15", va="center")
    tb.text(COLX[2], y, exp, fontsize=FS, color="0.15", va="center", ha="right")

pl.set_xlim(0.55, 2.55); pl.set_ylim(-1.9, n)
pl.axvspan(0.55, 1.0, color=GREY, zorder=0)
pl.axvline(1.0, color="0.25", lw=1.0, zorder=2)
pl.text(0.985, n - 1.62, "no change", fontsize=FS-0.5, color="0.35",
        ha="right", va="center")
for i, (kind, agent, system, exp, val, ref) in enumerate(ROWS):
    y = n - 1.5 - i
    if kind == "h":
        pl.plot([0.55, 2.55], [y - 0.5] * 2, color="0.80", lw=0.7)
        continue
    acid = agent in ACID
    col = AC if acid else BC
    if val > 1.001:
        pl.plot([1.0, val], [y, y], color=col, lw=1.4, alpha=0.75, zorder=3)
    pl.plot([val], [y], marker="s" if acid else "o", ms=8,
            color=col, zorder=4, clip_on=False)
    pl.text(2.52, y, ref, fontsize=FS, color="0.15", va="center", ha="right")
pl.text(2.52, n - 0.35, "Ref.", fontsize=FS, weight="bold",
        va="center", ha="right")
pl.plot([0.55, 2.55], [n - 0.85] * 2, color="0.25", lw=1.0, clip_on=False)

pl.set_yticks([])
pl.set_xticks([0.6, 1.0, 1.5, 2.0])
pl.tick_params(axis="x", labelsize=11)
pl.set_xlabel("NAD$^+$, fold of control", fontsize=FS, labelpad=6, x=0.42)
for sp in ("top", "right", "left"):
    pl.spines[sp].set_visible(False)
pl.spines["bottom"].set_position(("data", -0.35))

fig.legend(handles=[Line2D([], [], marker="s", ls="", ms=8, color=AC,
                           label="acid branch"),
                    Line2D([], [], marker="o", ls="", ms=8, color=BC,
                           label="amide branch")],
           loc="lower center", ncol=2, frameon=False,
           bbox_to_anchor=(0.52, -0.02), fontsize=FS)
# (Figure 1 of the manuscript is generated by PharmRes_Figure1.py)

# =========================================================== FIGURE 2
Ng = np.linspace(0.5, 320, 600)
Mg = np.linspace(0, 400, 800)


def fig3a(ax):   # manuscript Figure 3(a): the bounded gain
    ax.plot(Ng, sat(Ng), color=GY, lw=2.0)
    ax.axhline(1.0, color=LG, lw=0.9)
    ax.text(318, 1.02, "ceiling", fontsize=FS-0.5, color="0.35", ha="right")
    for N, c, lab in ((N_UN, AC, "unstressed"), (N_DP, BC, "UV-depleted")):
        ax.plot([N, N], [0, sat(N)], ls=":", color=c, lw=1.4)
        ax.plot([0, N], [sat(N)] * 2, ls=":", color=c, lw=1.4)
        ax.plot([N], [sat(N)], "o", ms=9, color=c, zorder=5)
    ax.text(112, 0.66, "unstressed\n$N_0$ = 100 \u00b5M\n$G_{max}$ = 1.29",
            fontsize=FS, color=AC, va="top")
    ax.text(40, 0.36, "UV-depleted\n$N_0$ = 25 \u00b5M\n$G_{max}$ = 2.16",
            fontsize=FS, color=BC, va="top")
    ax.set_xlim(0, 320); ax.set_ylim(0, 1.13)
    ax.set_xlabel("Nuclear free NAD$^+$, $N$ (\u00b5M)")
    ax.set_ylabel("SIRT1 output, fraction of $V_{max}$")
    ax.set_title("(a) the gain is bounded", loc="left", fontsize=FS)


def fig3b(ax):   # manuscript Figure 3(b): the unbounded penalty
    ax.axvspan(M_DP, 400, color=GREY, zorder=0)
    ax.plot(Mg, penalty(Mg), color=GY, lw=2.0, label="penalty $P(M)$")
    ax.plot(Mg, G_UN * penalty(Mg), color=AC, lw=2.4, ls="--",
            label="$G_{max}\\cdot P$, unstressed")
    ax.plot(Mg, G_DP * penalty(Mg), color=BC, lw=2.4, ls="--",
            label="$G_{max}\\cdot P$, UV-depleted")
    ax.axhline(1.0, color=LG, lw=0.9)
    for M, c in ((M_UN, AC), (M_DP, BC)):
        ax.plot([M], [1.0], "o", ms=10, mfc="white", mec=c, mew=2.0, zorder=5)
    ax.text(M_UN - 8, 1.28, "$M^*$ = 89 \u00b5M", fontsize=FS, color=AC, ha="right")
    ax.text(M_DP + 6, 1.42, "$M^*$ = 268 \u00b5M", fontsize=FS, color=BC)
    ax.text(396, 0.10, "no attainable NAD$^+$\nrestores baseline",
            fontsize=FS-0.5, color="0.40", ha="right", va="bottom")
    ax.set_xlim(0, 400); ax.set_ylim(0, 2.35)
    ax.set_xlabel("Intracellular nicotinamide, $M$ (\u00b5M)")
    ax.set_ylabel("Sirtuin output, relative to rest")
    ax.set_title("(b) the penalty is not", loc="left", fontsize=FS)
    ax.legend(frameon=False, loc="upper right", fontsize=FS-0.5,
              handlelength=1.7, borderpad=0.2)


for stem, fn in (("Figure3a", fig3a), ("Figure3b", fig3b)):
    f, a = plt.subplots(figsize=(W, W * 0.52))
    fn(a); a.spines[["top", "right"]].set_visible(False)
    f.tight_layout(); save(f, stem)

f, ax = plt.subplots(1, 2, figsize=(9.6, 4.15))
fig3a(ax[0]); fig3b(ax[1])
for a in ax:
    a.spines[["top", "right"]].set_visible(False)
f.tight_layout(); save(f, "Figure3")

# =========================================================== FIGURE 3
Ml = np.logspace(np.log10(M0), 3, 700)


def out_ratio(M, N0):
    N = N0 * (M / M0) ** ETA
    return gain(N, N0) * penalty(M)


def fig4a(ax):
    yu, yd = out_ratio(Ml, N_UN), out_ratio(Ml, N_DP)
    ax.fill_between(Ml, yu, 1.0, color=SHADE, zorder=0)
    ax.semilogx(Ml, yu, color=AC, lw=2.4, label="unstressed  $N_0$ = 100 \u00b5M")
    ax.semilogx(Ml, yd, color=BC, lw=2.6, ls="--",
                label="UV-depleted  $N_0$ = 25 \u00b5M")
    ax.axhline(1.0, color=GY, lw=1.0)
    Mp = Ml[np.argmax(yd)]
    ax.plot([Mp], [yd.max()], "o", ms=10, mfc="white", mec=BC, mew=2.0, zorder=5)
    for M, y, c, txt, dy in ((100, out_ratio(100, N_UN), AC, "\u221219%", -0.075),
                             (100, out_ratio(100, N_DP), BC, "\u22129%", 0.055)):
        ax.plot([M], [y], "o", ms=8, color=c, zorder=5)
        ax.text(118, y + dy, txt, fontsize=FS, color=c, weight="bold")
    ax.text(32, 1.11, "resting $M_0$ = 30 \u00b5M", fontsize=FS-0.5, color="0.40",
            va="top")
    ax.text(760, 0.62, "shortfall against\nbaseline output", fontsize=FS-0.5,
            color="0.40", style="italic", ha="right")
    ax.set_xlim(M0, 1000); ax.set_ylim(0.3, 1.14)
    ax.set_xlabel("Intracellular nicotinamide, $M$ (\u00b5M)")
    ax.set_ylabel("Sirtuin output, $A/A_0$")
    ax.set_title("(a) what the dose delivers", loc="left", fontsize=FS)
    ax.legend(frameon=False, loc="lower left", fontsize=FS-0.5, handlelength=1.9)


def fig4b(ax):
    Mb = np.logspace(0, np.log10(260), 700)
    eu, ed = eta_req(Mb, N_UN), eta_req(Mb, N_DP)
    ax.fill_between(Mb, 0, ed, color=GREY, zorder=0)
    ax.semilogx(Mb, eu, color=AC, lw=2.4)
    ax.semilogx(Mb, ed, color=BC, lw=2.6, ls="--")
    ax.axvline(M0, color="0.6", lw=1.0, ls=":")
    ax.text(1.12, 1.36, "measured \u03b7", fontsize=FS-0.5, color="0.35",
            style="italic")
    for eta, c, lab, ty in ((0.34, BC, "riboside, blood  0.34", 1.22),
                            (0.26, GY, "NAMPT 6\u00d7  0.26", 1.09),
                            (0.00, BC, "keratinocytes  0.00", 0.96)):
        ax.axhline(eta, color=c, lw=1.2)
        ax.text(1.12, ty, lab, fontsize=FS-0.5, color=c)
        if eta > 0:
            for N0, cc in ((N_UN, AC), (N_DP, BC)):
                Mi = eta * K_S * K_I / ((K_S + N0) - eta * K_S)
                ax.plot([Mi], [eta], "o", ms=9, mfc="white", mec=cc, mew=1.8,
                        zorder=5)
    ax.text(235, 0.70, "condition unmet\nin either state", fontsize=FS-0.5,
            color="0.40", style="italic", va="top", ha="right")
    ax.text(31, 2.30, "resting $M_0$", fontsize=FS-0.5, color="0.40", va="top")
    ax.text(3.4, 2.28, "threshold, unstressed", fontsize=FS, color=AC, va="top")
    ax.text(95, 1.30, "threshold,\nUV-depleted", fontsize=FS, color=BC)
    ax.set_xlim(1, 260); ax.set_ylim(0, 2.45)
    ax.set_xlabel("Intracellular nicotinamide, $M$ (\u00b5M)")
    ax.set_ylabel("Elasticity $\\eta$")
    ax.set_title("(b) what it would have to deliver", loc="left", fontsize=FS)


for stem, fn in (("Figure4a", fig4a), ("Figure4b", fig4b)):
    f, a = plt.subplots(figsize=(W, W * 0.52))
    fn(a); a.spines[["top", "right"]].set_visible(False)
    f.tight_layout(); save(f, stem)

f, ax = plt.subplots(1, 2, figsize=(9.6, 4.15))
fig4a(ax[0]); fig4b(ax[1])
for a in ax:
    a.spines[["top", "right"]].set_visible(False)
f.tight_layout(); save(f, "Figure4")

print("done")
